baseurl = "/"
languageCode = "en-us"
title = "Auto Doprava David"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
# Define how many posts should appear on a site
paginate = 2 
canonifyurls = true




 
 
